### ISSUE TITLE
Rewrite the frontend in vue 

### ISSUE THREAD

**Issue by BenjaminFont** [BenjaminFont/fussballArenaFinder#19]
We should rewrite the frontend with vueJS since the expertise of most of the members attending the hackergarten Stuttgart who do frontend dev. is with vue.

**Comment by bvanelli** [comment]
Closed by @OleksiiMalitskyi2014 pull requests https://github.com/BenjaminFont/fussballArenaFinder/pull/44 and https://github.com/BenjaminFont/fussballArenaFinder/pull/46
